### ISSUE TITLE
getting error with HNKGooglePlacesAutocomplete library

### ISSUE THREAD

**Issue by kirankota** [hkellaway/HNKGooglePlacesAutocomplete#103]
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation) . 

Please help me to come out from this.

**Comment by haidalinda** [comment]
im not sure what the issue is or if it's specific to this library as opposed to say CocoaPods. 

certainly try cleaning the project (Product > hold Option key > Clean Build Folder). try deleting you leave Pods/ directory and doing a fresh install.

past that, apologies - this library is no longer actively maintained
