### ISSUE TITLE
HNKGooglePlacesAutocompletePlace Question

### ISSUE THREAD

**Issue by jruston** [hkellaway/HNKGooglePlacesAutocomplete#96]
Hi,

When I have successfully fetched the places, how do I take the street number, locality and postal code from one of the returned HNKGooglePlacesAutocompletePlace objects?

I can see this object with types, substrings and terms arrays but no simple way of, eg, getting the postal code.

Thanks!

**Comment by haidalinda** [comment]
Postal code is not returned from the API. You can use the `CLPlacemark` extension (described here: https://github.com/hkellaway/HNKGooglePlacesAutocomplete#clplacemark-from-place) - `CLPlacemark` has a lot of additional information of that type.

**Comment by shortstuffsushi** [comment]
Hi there,

Just wanted to kind of expand on this question, as I am also confused. What is the use of the additional fields on the Place object? Is there any way to get useful information off the Place without the additional queries done by the CLPlacemark? Is the Place useful for anything besides starting additional queries?

**Comment by shortstuffsushi** [comment]
Looking into the actual [Google Autocomplete docs](https://developers.google.com/places/web-service/autocomplete), the response objects make more sense. Perhaps it's worth linking out there in the ReadMe or something so that people without a good understanding of the backing Autocomplete API are able to better interpret the responses.

**Comment by haidalinda** [comment]
good idea - ill add that
