### ISSUE TITLE
Getting error of iP address

### ISSUE THREAD

**Issue by BhaveshDhaduk** [hkellaway/HNKGooglePlacesAutocomplete#99]
Hello friend,

When i am running this project i am getting this error, can you please help me.
Here with attached screenshot of error.

![api](https://cloud.githubusercontent.com/assets/29055/21384721/b4fd5caa-c791-11e6-901b-54c936ca3fa8.png)

![abc](https://cloud.githubusercontent.com/assets/29055/21384633/5a194696-c791-11e6-9c3d-b72777a2702c.PNG)

**Comment by haidalinda** [comment]
i'm unfortunately not familiar with that error message, nor have i configured Google for use of this API in a while. However, I recall that it may not be the `iOS apps` setting you want, rather the one for web - as this is a library wrapping the API used for web.

**Comment by imranmunirawan** [comment]
i am experiencing with the same issue message, please help how to get rid off from this issue.

**Comment by haidalinda** [comment]
as mentioned - i'm not familiar with that error message, nor have i configured Google for use of this API in a while. 

However, I recall that it may not be the iOS apps setting you want, rather the one for web - as this is a library wrapping the API used for web.

Try configuring your API access for Web instead of iOS. That's the best advice i can give.

**Comment by nagam11** [comment]
I solved this in two ways:
1. Create an API Key with an IP restriction and enter your IP address under 'accept requests from these IPs'. This solution however, is very limited and maybe only for testing purposes.
2. Create an API Key with no restriction at all. The app worked same as before.

**Comment by Rj707** [comment]
the solution is to use web browser key, instead of mobile key.
